/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YukleRouteImport } from './routes/yukle'
import { Route as TasarlaRouteImport } from './routes/tasarla'
import { Route as SssRouteImport } from './routes/sss'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHesapRouteImport } from './routes/_authenticated/hesap'
import { Route as AuthenticatedHesapIndexRouteImport } from './routes/_authenticated/hesap.index'

const YukleRoute = YukleRouteImport.update({
  id: '/yukle',
  path: '/yukle',
  getParentRoute: () => rootRouteImport,
} as any)
const TasarlaRoute = TasarlaRouteImport.update({
  id: '/tasarla',
  path: '/tasarla',
  getParentRoute: () => rootRouteImport,
} as any)
const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHesapRoute = AuthenticatedHesapRouteImport.update({
  id: '/hesap',
  path: '/hesap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHesapIndexRoute = AuthenticatedHesapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHesapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sepet': typeof SepetRoute
  '/sss': typeof SssRoute
  '/tasarla': typeof TasarlaRoute
  '/yukle': typeof YukleRoute
  '/hesap': typeof AuthenticatedHesapRouteWithChildren
  '/hesap/': typeof AuthenticatedHesapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sepet': typeof SepetRoute
  '/sss': typeof SssRoute
  '/tasarla': typeof TasarlaRoute
  '/yukle': typeof YukleRoute
  '/hesap': typeof AuthenticatedHesapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sepet': typeof SepetRoute
  '/sss': typeof SssRoute
  '/tasarla': typeof TasarlaRoute
  '/yukle': typeof YukleRoute
  '/_authenticated/hesap': typeof AuthenticatedHesapRouteWithChildren
  '/_authenticated/hesap/': typeof AuthenticatedHesapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/odeme'
    | '/reset-password'
    | '/sepet'
    | '/sss'
    | '/tasarla'
    | '/yukle'
    | '/hesap'
    | '/hesap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/odeme'
    | '/reset-password'
    | '/sepet'
    | '/sss'
    | '/tasarla'
    | '/yukle'
    | '/hesap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/odeme'
    | '/reset-password'
    | '/sepet'
    | '/sss'
    | '/tasarla'
    | '/yukle'
    | '/_authenticated/hesap'
    | '/_authenticated/hesap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GaleriRoute: typeof GaleriRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  OdemeRoute: typeof OdemeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SepetRoute: typeof SepetRoute
  SssRoute: typeof SssRoute
  TasarlaRoute: typeof TasarlaRoute
  YukleRoute: typeof YukleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yukle': {
      id: '/yukle'
      path: '/yukle'
      fullPath: '/yukle'
      preLoaderRoute: typeof YukleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasarla': {
      id: '/tasarla'
      path: '/tasarla'
      fullPath: '/tasarla'
      preLoaderRoute: typeof TasarlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hesap': {
      id: '/_authenticated/hesap'
      path: '/hesap'
      fullPath: '/hesap'
      preLoaderRoute: typeof AuthenticatedHesapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hesap/': {
      id: '/_authenticated/hesap/'
      path: '/'
      fullPath: '/hesap/'
      preLoaderRoute: typeof AuthenticatedHesapIndexRouteImport
      parentRoute: typeof AuthenticatedHesapRoute
    }
  }
}

interface AuthenticatedHesapRouteChildren {
  AuthenticatedHesapIndexRoute: typeof AuthenticatedHesapIndexRoute
}

const AuthenticatedHesapRouteChildren: AuthenticatedHesapRouteChildren = {
  AuthenticatedHesapIndexRoute: AuthenticatedHesapIndexRoute,
}

const AuthenticatedHesapRouteWithChildren =
  AuthenticatedHesapRoute._addFileChildren(AuthenticatedHesapRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHesapRoute: typeof AuthenticatedHesapRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHesapRoute: AuthenticatedHesapRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GaleriRoute: GaleriRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  OdemeRoute: OdemeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SepetRoute: SepetRoute,
  SssRoute: SssRoute,
  TasarlaRoute: TasarlaRoute,
  YukleRoute: YukleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
